update

tap homebrew/binary
tap ysakmrkm/homebrew-cask
# PHP
tap homebrew/dupes
tap josegonzalez/homebrew-php
tap caskroom/fonts

install cpanminus
install git
install git-flow
install git-ftp
install jq
# pythonのpygit2のインストールに必要
install libgit2
# grunt-image使用に必要
install libjpeg libjpeg-turbo libpng
# git pagerで利用
install lv
install macvim --with-python --override-system-vim
# phpmyadminのインストールに必要
install mcrypt autoconf
install mysql
install node
install python
install phpmyadmin
install reattach-to-user-namespace
install redis
install ruby
install tmux

install brew-cask

cask install font-source-code-pro
cask install font-sauce-code-powerline

cask install alfred
cask install appcleaner
cask install charles
cask install cursorsense
cask install day-o
cask install dropbox
cask install filezilla
cask install firefox
cask install google-chrome
cask install google-japanese-ime
cask install growlnotify
cask install hyperswitch
cask install iterm2
cask install keyremap4macbook
cask install mou
cask install p4merge
cask install sourcetree
cask install totalfinder
cask install transmit
cask install vmware-fusion

cask link alfred link

linkapps

cleanup
