update

tap homebrew/binary
tap ysakmrkm/homebrew-cask
tap caskroom/fonts

install git
install git-flow
install git-ftp
install tmux
install reattach-to-user-namespace
install macvim --with-python
install node
install python
install ruby
#pythonのpygit2のインストールに必要
install mysql
install libgit2

install brew-cask

cask install font-source-code-pro
cask install font-sauce-code-powerline

cask install alfred
cask install appcleaner
cask install charles
cask install cursorsense
cask install day-o
cask install dropbox
cask install filezilla
cask install firefox
cask install google-chrome
cask install google-japanese-ime
cask install hyperswitch
cask install iterm2
cask install keyremap4macbook
cask install mou
cask install p4merge
cask install sourcetree
cask install totalfinder
cask install vmware-fusion

cask link alfred link

linkapps

cleanup
